; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32_one]
platform = espressif32
board = waveshare_esp32_one
framework = arduino
upload_port = COM3
upload_speed = 921600
monitor_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_I2S_ISR_IRAM_SAFE=1
    -DAUDIO_BUFFER_SIZE=8192
    -DI2S_BUFFER_COUNT=8
    -DCONFIG_FREERTOS_OPTIMIZATION_LEVEL=3
    -DCONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=8192
    -DCONFIG_FREERTOS_UNICORE=n
    -DCONFIG_ESP_TASK_WDT_TIMEOUT_SEC=30    ; Increased timeout
    -DCONFIG_ESP_INT_WDT=n                  ; Disable interrupt watchdog
    -DCONFIG_ESP_TASK_WDT=n                 ; Disable task watchdog
lib_deps = 
    sparkfun/SparkFun WM8960 Arduino Library @ ^1.0.3